class ActiveRecord::Base
   def international_normalize(str)
     n = str.strip.to_s
     n.gsub!(/[àáâãäåāă]/,    'a')
     n.gsub!(/[ÀÁÂÃÄÅĀĂ]/,    'A')
     n.gsub!(/æ/,            'ae')
     n.gsub!(/Æ/,            'AE')
     n.gsub!(/[ďđ]/,          'd')
     n.gsub!(/[ĎĐ]/,          'D')
     n.gsub!(/[çćčĉċ]/,       'c')
     n.gsub!(/[ÇĆČĈĊ]/,       'C')
     n.gsub!(/[èéêëēęěĕė]/,   'e')
     n.gsub!(/[ÈÉÊËĒĘĚĔĖ]/,   'E')
     n.gsub!(/ƒ/,             'f')
     n.gsub!(/Ƒ/,             'F')
     n.gsub!(/[ĝğġģ]/,        'g')
     n.gsub!(/[ĜĞĠĢ]/,        'G')
     n.gsub!(/[ĥħ]/,           'h')
     n.gsub!(/[ĤĦ]/,           'H')
     n.gsub!(/[ıììíîïīĩĭ]/,    'i')
     n.gsub!(/[İÌÍÎÏĪĨĬ]/,    'I')
     n.gsub!(/[įĳĵ]/,        'j')
     n.gsub!(/[ĮĲĴ]/,        'J')
     n.gsub!(/[ķĸ]/,          'k')
     n.gsub!(/[Ķĸ]/,          'K')
     n.gsub!(/[łľĺļŀ]/,       'l')
     n.gsub!(/[ŁĽĹĻĿ]/,       'L')
     n.gsub!(/[ñńňņŉŋ]/,      'n')
     n.gsub!(/[ÑŃŇŅʼNŊ]/,      'N')
     n.gsub!(/[òóôõöøōőŏŏ]/,  'o')
     n.gsub!(/[ÒÓÔÕÖØŌŐŎŎ]/,  'O')
     n.gsub!(/œ/,            'oe')
     n.gsub!(/Œ/,            'OE')
     n.gsub!(/ą/,             'q')
     n.gsub!(/Ą/,             'Q')
     n.gsub!(/[ŕřŗ]/,         'r')
     n.gsub!(/[ŔŘŖ]/,         'R')
     n.gsub!(/[śšşŝș]/,       's')
     n.gsub!(/[ŚŠŞŜȘ]/,       'S')
     n.gsub!(/[ťţŧț]/,        't')
     n.gsub!(/[ŤŢŦȚ]/,        'T')
     n.gsub!(/[ùúûüūůűŭũų]/,  'u')
     n.gsub!(/[ÙÚÛÜŪŮŰŬŨŲ]/,  'U')
     n.gsub!(/ŵ/,             'w')
     n.gsub!(/Ŵ/,             'W')
     n.gsub!(/[ýÿŷ]/,         'y')
     n.gsub!(/[ÝŸŶ]/,         'Y')
     n.gsub!(/[žżź]/,         'z')
     n.gsub!(/[ŽŻŹ]/,         'Z')
     n.gsub!(/\s+/,            '-')
     n.gsub!(/[^\sA-Za-z0-9_-]/,   '')
     return n.downcase
   end
   def to_seo_compatible_param(str)
    "#{self.id}_#{international_normalize(str)}"
   end
end
