defaults: &defaults
 url: http://localhost:8080/rsx-mobile-service-test_servlet-0.1/test/?bindurl=http://localhost:3000
 ttl: 30

development:
 <<: *defaults

test:
 <<: *defaults

staging:
 <<: *defaults

production:
 <<: *defaults
